### ISSUE TITLE
Suggestion for API_URL parameter

### ISSUE THREAD

**Issue by rush1818** [mirakl/tag-gtm-template#2]
Hi,

This is a non-blocking suggestion. Consider changing the `API_URL` parameter to a select dropdown with the values you expect.

**Comment by euphocat** [comment]
Hello @rush1818 

Thank you again for you feedback. We have decided to leave `API_URL` as a plain text field because we need this flexibility (several environnements). But we have added a default value, and it's now optional.

Is everything ok on your side for a publication ?
